import { tsType, type Entity } from './entities';

/**
 * The app's data and sign-in code, generated by Forge — not by the model
 * (BUILD-PROMPT M4). Every entity file change rewrites these deterministically:
 * no tokens, no hallucinated endpoints, and the types always match the rules
 * the server enforces.
 *
 * They live in src/forge/, which the model may read but never write.
 */

export const FORGE_DIR = 'src/forge/';
export const DATA_FILE = 'src/forge/data.ts';
export const AUTH_FILE = 'src/forge/auth.tsx';

const HEADER = `/* Generated by Forge from entities/*.json — do not edit.
   Forge rewrites this file whenever the data model changes. */`;

const RUNTIME = `export class DataError extends Error {
  constructor(
    readonly status: number,
    message: string,
  ) {
    super(message);
  }
}

/** Filters a query understands. A bare value means "is equal to". */
export type Condition = string | number | boolean | null | { op: 'eq' | 'ne' | 'gt' | 'gte' | 'lt' | 'lte' | 'contains' | 'in'; value: unknown };

export interface Query<T> {
  where?: Partial<Record<keyof T & string, Condition>>;
  /** "title" or "-createdAt" for newest first. */
  sort?: string;
  limit?: number;
  cursor?: string;
}

const BASE = '/_forge/data';

async function send<T>(method: string, url: string, body?: unknown): Promise<T> {
  const res = await fetch(url, {
    method,
    credentials: 'same-origin',
    headers: body === undefined ? undefined : { 'content-type': 'application/json' },
    body: body === undefined ? undefined : JSON.stringify(body),
  });
  const text = await res.text();
  const payload = (text ? JSON.parse(text) : {}) as { error?: string };
  if (!res.ok) throw new DataError(res.status, payload.error ?? \`Request failed (\${res.status})\`);
  return payload as T;
}

function search<T>(query: Query<T>): string {
  return Object.keys(query).length ? \`?q=\${encodeURIComponent(JSON.stringify(query))}\` : '';
}

/** The methods every entity gets. Access rules are enforced on the server. */
function collection<T, I>(name: string) {
  const one = (id: string) => \`\${BASE}/\${name}/\${encodeURIComponent(id)}\`;
  return {
    /** Rows you are allowed to see, newest first unless you sort. */
    async list(query: Query<T> = {}): Promise<T[]> {
      return (await send<{ rows: T[] }>('GET', \`\${BASE}/\${name}\${search(query)}\`)).rows;
    },
    /** Like list(), with a cursor for the next page. */
    async page(query: Query<T> = {}): Promise<{ rows: T[]; nextCursor?: string }> {
      return send<{ rows: T[]; nextCursor?: string }>('GET', \`\${BASE}/\${name}\${search(query)}\`);
    },
    async get(id: string): Promise<T> {
      return (await send<{ row: T }>('GET', one(id))).row;
    },
    async create(input: I): Promise<T> {
      return (await send<{ row: T }>('POST', \`\${BASE}/\${name}\`, input)).row;
    },
    async update(id: string, input: Partial<I>): Promise<T> {
      return (await send<{ row: T }>('PATCH', one(id), input)).row;
    },
    async remove(id: string): Promise<void> {
      await send<unknown>('DELETE', one(id));
    },
  };
}`;

function rowInterface(entity: Entity): string {
  const lines = [
    `export interface ${entity.name} {`,
    '  id: string;',
    '  /** The user who created this row, or null if it was created signed out. */',
    '  ownerId: string | null;',
    '  createdAt: string;',
    '  updatedAt: string;',
  ];
  for (const [name, field] of Object.entries(entity.fields)) {
    const type = tsType(field);
    lines.push(`  ${name}: ${field.required ? type : `${type} | null`};`);
  }
  lines.push('}');
  return lines.join('\n');
}

function inputInterface(entity: Entity): string {
  const lines = [`export interface ${entity.name}Input {`];
  for (const [name, field] of Object.entries(entity.fields)) {
    const type = tsType(field);
    lines.push(field.required ? `  ${name}: ${type};` : `  ${name}?: ${type} | null;`);
  }
  lines.push('}');
  return lines.join('\n');
}

/** src/forge/data.ts: one typed collection per entity, plus the fetch runtime. */
export function generateData(entities: Entity[]): string {
  const sorted = [...entities].sort((a, b) => a.name.localeCompare(b.name));
  const parts = [HEADER, '', RUNTIME, ''];
  for (const entity of sorted) {
    parts.push(rowInterface(entity), '', inputInterface(entity), '');
    parts.push(`/** ${entity.label ?? entity.name}. Who may do what: ${describe(entity)} */`);
    parts.push(`export const ${entity.name} = collection<${entity.name}, ${entity.name}Input>('${entity.name}');`, '');
  }
  return parts.join('\n');
}

function describe(entity: Entity): string {
  const say = { everyone: 'anyone', user: 'any signed-in user', owner: 'the owner only', nobody: 'no one' } as const;
  return (['read', 'create', 'update', 'delete'] as const).map((a) => `${a} — ${say[entity.access[a]]}`).join('; ');
}

/** src/forge/auth.tsx: the same sign-in for every app, so no one has to write one. */
export function generateAuth(): string {
  return `${HEADER}
import { useCallback, useEffect, useState, useSyncExternalStore, type FormEvent, type ReactNode } from 'react';

export interface AppUser {
  id: string;
  email: string;
}

const BASE = '/_forge/auth';

interface AuthState {
  user: AppUser | null;
  loading: boolean;
}

let state: AuthState = { user: null, loading: true };
const listeners = new Set<() => void>();
let started = false;

function set(next: AuthState) {
  state = next;
  for (const listener of listeners) listener();
}

function subscribe(listener: () => void) {
  listeners.add(listener);
  return () => {
    listeners.delete(listener);
  };
}

async function call<T>(path: string, body?: unknown): Promise<T> {
  const res = await fetch(BASE + path, {
    method: body === undefined ? 'GET' : 'POST',
    credentials: 'same-origin',
    headers: body === undefined ? undefined : { 'content-type': 'application/json' },
    body: body === undefined ? undefined : JSON.stringify(body),
  });
  const text = await res.text();
  const payload = (text ? JSON.parse(text) : {}) as { error?: string };
  if (!res.ok) throw new Error(payload.error ?? 'Something went wrong. Try again.');
  return payload as T;
}

/** Ask the server who is signed in; safe to call as often as you like. */
export async function refreshUser(): Promise<AppUser | null> {
  try {
    const { user } = await call<{ user: AppUser | null }>('/me');
    set({ user, loading: false });
    return user;
  } catch {
    set({ user: null, loading: false });
    return null;
  }
}

export async function signOut(): Promise<void> {
  await call<unknown>('/signout', {});
  set({ user: null, loading: false });
}

/** The signed-in user, or null. Re-renders when that changes. */
export function useUser(): AuthState & { signOut: () => Promise<void>; refresh: () => Promise<AppUser | null> } {
  const snapshot = useSyncExternalStore(
    subscribe,
    () => state,
    () => state,
  );
  useEffect(() => {
    if (started) return;
    started = true;
    void refreshUser();
  }, []);
  return { ...snapshot, signOut, refresh: refreshUser };
}

/** Email + six-digit code. No passwords, nothing to reset. */
export function SignIn({ title = 'Sign in', description = 'We will email you a six-digit code.' }: { title?: string; description?: string }) {
  const [email, setEmail] = useState('');
  const [code, setCode] = useState('');
  const [sent, setSent] = useState(false);
  const [hint, setHint] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [busy, setBusy] = useState(false);

  const request = useCallback(
    async (e: FormEvent) => {
      e.preventDefault();
      setBusy(true);
      setError(null);
      try {
        const res = await call<{ delivery: string; code?: string }>('/code', { email });
        setSent(true);
        setHint(res.code ? 'Preview mode — your code is ' + res.code : 'Check your email for the code.');
      } catch (err) {
        setError((err as Error).message);
      } finally {
        setBusy(false);
      }
    },
    [email],
  );

  const verify = useCallback(
    async (e: FormEvent) => {
      e.preventDefault();
      setBusy(true);
      setError(null);
      try {
        const { user } = await call<{ user: AppUser }>('/verify', { email, code });
        set({ user, loading: false });
      } catch (err) {
        setError((err as Error).message);
      } finally {
        setBusy(false);
      }
    },
    [email, code],
  );

  const field = 'w-full rounded-lg border border-slate-200 bg-white px-3 py-2 text-sm text-slate-900 outline-none focus:border-slate-400';
  const button = 'w-full rounded-lg bg-slate-900 px-3 py-2 text-sm font-medium text-white transition hover:bg-slate-700 disabled:opacity-60';

  return (
    <form onSubmit={sent ? verify : request} className="mx-auto flex w-full max-w-sm flex-col gap-3 rounded-xl border border-slate-200 bg-white p-5 shadow-sm">
      <div>
        <h2 className="text-base font-semibold text-slate-900">{title}</h2>
        <p className="mt-1 text-sm text-slate-500">{description}</p>
      </div>
      <input
        type="email"
        required
        value={email}
        onChange={(e) => setEmail(e.target.value)}
        placeholder="you@example.com"
        autoComplete="email"
        disabled={sent}
        className={field}
      />
      {sent && (
        <input
          inputMode="numeric"
          required
          value={code}
          onChange={(e) => setCode(e.target.value.replace(/[^0-9]/g, '').slice(0, 6))}
          placeholder="123456"
          autoComplete="one-time-code"
          className={field + ' tracking-[0.3em]'}
        />
      )}
      <button type="submit" disabled={busy} className={button}>
        {busy ? 'Working…' : sent ? 'Sign in' : 'Email me a code'}
      </button>
      {hint && !error && <p className="text-xs text-slate-500">{hint}</p>}
      {error && <p className="text-xs text-rose-600">{error}</p>}
      {sent && !busy && (
        <button
          type="button"
          onClick={() => {
            setSent(false);
            setCode('');
            setHint(null);
          }}
          className="text-xs text-slate-500 underline"
        >
          Use a different email
        </button>
      )}
    </form>
  );
}

/** Shows the sign-in form until someone is signed in, then the children. */
export function RequireSignIn({ children, title, description }: { children: ReactNode; title?: string; description?: string }) {
  const { user, loading } = useUser();
  if (loading) return <div className="p-8 text-sm text-slate-400">Loading…</div>;
  if (!user) {
    return (
      <div className="flex min-h-screen items-center justify-center bg-slate-50 p-6">
        <SignIn title={title} description={description} />
      </div>
    );
  }
  return <>{children}</>;
}
`;
}

/** Every file Forge owns for this data model. */
export function generateClient(entities: Entity[]): { path: string; content: string }[] {
  if (!entities.length) return [];
  return [
    { path: DATA_FILE, content: generateData(entities) },
    { path: AUTH_FILE, content: generateAuth() },
  ];
}
